language: go

go:
  - 1.11

sudo: false

git:
  depth: false

branches:
  only:
    - sourcefiles

env:
  global:
    - SOURCE_DIR="public"
    - BUILD_BRANCH="sourcefiles"
    - DEPLOY_BRANCH="master"
    - HUGO_BUILD_TAGS="extended"

install:
  - mkdir -p $HOME/src
  - mv $HOME/gopath/src/github.com/gohugoio/hugo $HOME/src
  - export TRAVIS_BUILD_DIR=$HOME/src/hugo
  - cd $HOME/src/hugo
  - go get github.com/magefile/mage  
script:
  - go mod download
  - mage -v test
  - mage -v check
  - mage -v hugo
- ./hugo 

deploy:
  provider: pages
  edge: true
  github_token: ${GITHUB_TOKEN}
  local_dir: public
  skip_cleanup: true
  traget_branch: master
  on:
    branch: sourcefiles

before_install:
  - gem install asciidoctor
  - type asciidoctor    
