language: go

go:
  - 1.11

sudo: false

git:
  depth: false

branches:
  only:
    - sourcefiles

env:
  global:
    - SOURCE_DIR="public"
    - BUILD_BRANCH="sourcefiles"
    - DEPLOY_BRANCH="master"
    - HUGO_BUILD_TAGS="extended"

install:
  - mkdir -p $HOME/src
  - go get github.com/magefile/mage
  - go get github.com/gohugoio/hugo
  - mv $HOME/gopath/src/github.com/gohugoio/hugo $HOME/src
  - cd $HOME/src/hugo
  
script:
  - go mod download
  - mage -v hugo 
  - ./hugo -s ${TRAVIS_HOME}/gopath/src/github.com/khangchendzonga/khangchendzonga.github.io

deploy:
  provider: pages
  edge: true
  github_token: ${GITHUB_TOKEN}
  local_dir: public
  skip_cleanup: true
  target_branch: master
  on:
    branch: sourcefiles

before_install:
  - gem install asciidoctor
  - type asciidoctor    
