theme = "hugo-now-ui"
baseurl = "/"
languageCode = "en-us"
title = "Himalayan Borderlands"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
background = "/images/bg.jpg"
#enableGitInfo = true
# publishDir = "../docs"
# themesDir = "../.."

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Team"
    url = "/page/team"
    pre = "<i class='now-ui-icons design_app'></i>"
    weight = 1
[[menu.main]]
    name = "Events"
    url = "/page/events"
    pre = "<i class='now-ui-icons business_bank'></i>"
    weight = 1

[params]
    background = "/images/bg.jpg"
    tint = "blue"
    # custom_css = ["css/highlight.min.css"]
    # custom_js = []
    date_format = "Mon, Jan 2, 2006"
    description = "Mountain Culutres and Travel Histories in the Eastern Himalaya"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.10.0"
    highlightCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"
